---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Set Default Policy to Deny Incoming
  ufw:
    direction: incoming
    policy: deny

- name: Allow SSH with Rate Limiting
  ufw:
    rule: limit
    port: "{{ item }}"
    proto: tcp
  loop: "{{ allowed_ports }}"

- name: Enable UFW
  ufw:
    state: enabled

- name: PANIC MODE
  iptables:
    chain: INPUT
    destination_port: "22"
    protocol: tcp
    jump: DROP
  when: panic_mode | bool

- name: PANIC MODE 2
  iptables:
    chain: INPUT
    destination_port: "80"
    protocol: tcp
    jump: DROP
  when: panic_mode | bool